#!/usr/bin/env python3
"""
make_version_file.py

Generate a PyInstaller "--version-file" resource so the built .exe shows
proper version details in Windows (right-click > Properties > Details).

Usage:
    python make_version_file.py <version> <app_name> <output_path>

<version> is a dotted version like "1.0.0" or "1.2.3.4". It is normalized
to the 4-part (major, minor, patch, build) tuple Windows requires; missing
parts are filled with 0 and extra parts are ignored.

This script uses only the standard library so it runs under the same pinned
build interpreter without extra dependencies.
"""

import sys


COMPANY_NAME = "Code-2-TXT"
PRODUCT_NAME = "Code-2-TXT"
DESCRIPTION = "Combine text/script files into a structured text dump"


def parse_version(raw: str):
    """Return a 4-int tuple from a dotted version string."""
    parts = []
    for chunk in raw.strip().split("."):
        chunk = chunk.strip()
        if not chunk:
            continue
        # Keep leading digits only (tolerates things like '1rc1').
        digits = ""
        for ch in chunk:
            if ch.isdigit():
                digits += ch
            else:
                break
        parts.append(int(digits) if digits else 0)
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])


def build_version_file(version_tuple, app_name: str) -> str:
    a, b, c, d = version_tuple
    ver_str = f"{a}.{b}.{c}.{d}"
    # PyInstaller version-info template (a Python literal it evals).
    return f"""# UTF-8
#
# Auto-generated by make_version_file.py - do not edit by hand.
# Regenerate via BUILD_EXE.bat (driven by version.txt).
#
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({a}, {b}, {c}, {d}),
    prodvers=({a}, {b}, {c}, {d}),
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'{COMPANY_NAME}'),
            StringStruct(u'FileDescription', u'{DESCRIPTION}'),
            StringStruct(u'FileVersion', u'{ver_str}'),
            StringStruct(u'InternalName', u'{app_name}'),
            StringStruct(u'OriginalFilename', u'{app_name}.exe'),
            StringStruct(u'ProductName', u'{PRODUCT_NAME}'),
            StringStruct(u'ProductVersion', u'{ver_str}')
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def main():
    if len(sys.argv) < 4:
        print("Usage: make_version_file.py <version> <app_name> <output_path>",
              file=sys.stderr)
        return 2
    raw_version = sys.argv[1]
    app_name = sys.argv[2]
    out_path = sys.argv[3]

    vt = parse_version(raw_version)
    content = build_version_file(vt, app_name)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {out_path} for version {'.'.join(str(x) for x in vt)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
